package com.lh.dao;

import com.lh.entity.CourseMedia;

public interface CourseMediaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_media
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_media
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    int insert(CourseMedia row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_media
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    int insertSelective(CourseMedia row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_media
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    CourseMedia selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_media
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    int updateByPrimaryKeySelective(CourseMedia row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_media
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    int updateByPrimaryKey(CourseMedia row);
}