package com.lh.dao;

import com.lh.entity.CourseSection;

public interface CourseSectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_section
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_section
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    int insert(CourseSection row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_section
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    int insertSelective(CourseSection row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_section
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    CourseSection selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_section
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    int updateByPrimaryKeySelective(CourseSection row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course_section
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    int updateByPrimaryKey(CourseSection row);
}