package com.lh.dao;

import com.lh.entity.PayOrderRecord;

public interface PayOrderRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_record
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_record
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    int insert(PayOrderRecord row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_record
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    int insertSelective(PayOrderRecord row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_record
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    PayOrderRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_record
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    int updateByPrimaryKeySelective(PayOrderRecord row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pay_order_record
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    int updateByPrimaryKey(PayOrderRecord row);
}