package com.lh.dao;

import com.lh.entity.PromotionAd;

public interface PromotionAdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotion_ad
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotion_ad
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    int insert(PromotionAd row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotion_ad
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    int insertSelective(PromotionAd row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotion_ad
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    PromotionAd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotion_ad
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    int updateByPrimaryKeySelective(PromotionAd row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotion_ad
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(PromotionAd row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table promotion_ad
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    int updateByPrimaryKey(PromotionAd row);
}