package com.lh.dao;

import com.lh.entity.UserCourseOrder;

public interface UserCourseOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course_order
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course_order
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    int insert(UserCourseOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course_order
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    int insertSelective(UserCourseOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course_order
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    UserCourseOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course_order
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    int updateByPrimaryKeySelective(UserCourseOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_course_order
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    int updateByPrimaryKey(UserCourseOrder row);
}