package com.lh.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   活动课程表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table activity_course
 */
public class ActivityCourse {
    /**
     * Database Column Remarks:
     *   主键ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_course.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   课程ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_course.course_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer courseId;

    /**
     * Database Column Remarks:
     *   活动开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_course.begin_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Date beginTime;

    /**
     * Database Column Remarks:
     *   活动结束时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_course.end_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Date endTime;

    /**
     * Database Column Remarks:
     *   活动价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_course.amount
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Double amount;

    /**
     * Database Column Remarks:
     *   库存值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_course.stock
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer stock;

    /**
     * Database Column Remarks:
     *   状态 0未上架 10已上架
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_course.status
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   逻辑删除 0未删除 1删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_course.is_del
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Boolean isDel;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_course.remark
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_course.create_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_course.create_user
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String createUser;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_course.update_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   更新人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_course.update_user
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_course.id
     *
     * @return the value of activity_course.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_course.id
     *
     * @param id the value for activity_course.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_course.course_id
     *
     * @return the value of activity_course.course_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_course.course_id
     *
     * @param courseId the value for activity_course.course_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_course.begin_time
     *
     * @return the value of activity_course.begin_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_course.begin_time
     *
     * @param beginTime the value for activity_course.begin_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_course.end_time
     *
     * @return the value of activity_course.end_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_course.end_time
     *
     * @param endTime the value for activity_course.end_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_course.amount
     *
     * @return the value of activity_course.amount
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_course.amount
     *
     * @param amount the value for activity_course.amount
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_course.stock
     *
     * @return the value of activity_course.stock
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_course.stock
     *
     * @param stock the value for activity_course.stock
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_course.status
     *
     * @return the value of activity_course.status
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_course.status
     *
     * @param status the value for activity_course.status
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_course.is_del
     *
     * @return the value of activity_course.is_del
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_course.is_del
     *
     * @param isDel the value for activity_course.is_del
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_course.remark
     *
     * @return the value of activity_course.remark
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_course.remark
     *
     * @param remark the value for activity_course.remark
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_course.create_time
     *
     * @return the value of activity_course.create_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_course.create_time
     *
     * @param createTime the value for activity_course.create_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_course.create_user
     *
     * @return the value of activity_course.create_user
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_course.create_user
     *
     * @param createUser the value for activity_course.create_user
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_course.update_time
     *
     * @return the value of activity_course.update_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_course.update_time
     *
     * @param updateTime the value for activity_course.update_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_course.update_user
     *
     * @return the value of activity_course.update_user
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_course.update_user
     *
     * @param updateUser the value for activity_course.update_user
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}