package com.lh.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   课程留言表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table course_comment
 */
public class CourseComment {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   课程id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.course_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer courseId;

    /**
     * Database Column Remarks:
     *   章节id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.section_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer sectionId;

    /**
     * Database Column Remarks:
     *   课时id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.lesson_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer lessonId;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.user_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   运营设置用户昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.user_name
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String userName;

    /**
     * Database Column Remarks:
     *   父级评论id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.parent_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer parentId;

    /**
     * Database Column Remarks:
     *   是否置顶：0不置顶，1置顶
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.is_top
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Boolean isTop;

    /**
     * Database Column Remarks:
     *   点赞数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.like_count
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer likeCount;

    /**
     * Database Column Remarks:
     *   是否回复留言：0普通留言，1回复留言
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.is_reply
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Boolean isReply;

    /**
     * Database Column Remarks:
     *   留言类型：0用户留言，1讲师留言，2运营马甲 3讲师回复 4小编回复 5官方客服回复
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.type
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer type;

    /**
     * Database Column Remarks:
     *   留言状态：0待审核，1审核通过，2审核不通过，3已删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.status
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.create_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.update_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   是否删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.is_del
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Boolean isDel;

    /**
     * Database Column Remarks:
     *   最后操作者id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.last_operator
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer lastOperator;

    /**
     * Database Column Remarks:
     *   是否发送了通知,1表示未发出，0表示已发出
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.is_notify
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Boolean isNotify;

    /**
     * Database Column Remarks:
     *   标记归属
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.mark_belong
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Boolean markBelong;

    /**
     * Database Column Remarks:
     *   回复状态 0 未回复 1 已回复
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.replied
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Boolean replied;

    /**
     * Database Column Remarks:
     *   评论
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment.comment
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.id
     *
     * @return the value of course_comment.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.id
     *
     * @param id the value for course_comment.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.course_id
     *
     * @return the value of course_comment.course_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.course_id
     *
     * @param courseId the value for course_comment.course_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.section_id
     *
     * @return the value of course_comment.section_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.section_id
     *
     * @param sectionId the value for course_comment.section_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setSectionId(Integer sectionId) {
        this.sectionId = sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.lesson_id
     *
     * @return the value of course_comment.lesson_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getLessonId() {
        return lessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.lesson_id
     *
     * @param lessonId the value for course_comment.lesson_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setLessonId(Integer lessonId) {
        this.lessonId = lessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.user_id
     *
     * @return the value of course_comment.user_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.user_id
     *
     * @param userId the value for course_comment.user_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.user_name
     *
     * @return the value of course_comment.user_name
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.user_name
     *
     * @param userName the value for course_comment.user_name
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.parent_id
     *
     * @return the value of course_comment.parent_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.parent_id
     *
     * @param parentId the value for course_comment.parent_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.is_top
     *
     * @return the value of course_comment.is_top
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Boolean getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.is_top
     *
     * @param isTop the value for course_comment.is_top
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setIsTop(Boolean isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.like_count
     *
     * @return the value of course_comment.like_count
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.like_count
     *
     * @param likeCount the value for course_comment.like_count
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.is_reply
     *
     * @return the value of course_comment.is_reply
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Boolean getIsReply() {
        return isReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.is_reply
     *
     * @param isReply the value for course_comment.is_reply
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setIsReply(Boolean isReply) {
        this.isReply = isReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.type
     *
     * @return the value of course_comment.type
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.type
     *
     * @param type the value for course_comment.type
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.status
     *
     * @return the value of course_comment.status
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.status
     *
     * @param status the value for course_comment.status
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.create_time
     *
     * @return the value of course_comment.create_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.create_time
     *
     * @param createTime the value for course_comment.create_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.update_time
     *
     * @return the value of course_comment.update_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.update_time
     *
     * @param updateTime the value for course_comment.update_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.is_del
     *
     * @return the value of course_comment.is_del
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.is_del
     *
     * @param isDel the value for course_comment.is_del
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.last_operator
     *
     * @return the value of course_comment.last_operator
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getLastOperator() {
        return lastOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.last_operator
     *
     * @param lastOperator the value for course_comment.last_operator
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setLastOperator(Integer lastOperator) {
        this.lastOperator = lastOperator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.is_notify
     *
     * @return the value of course_comment.is_notify
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Boolean getIsNotify() {
        return isNotify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.is_notify
     *
     * @param isNotify the value for course_comment.is_notify
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setIsNotify(Boolean isNotify) {
        this.isNotify = isNotify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.mark_belong
     *
     * @return the value of course_comment.mark_belong
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Boolean getMarkBelong() {
        return markBelong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.mark_belong
     *
     * @param markBelong the value for course_comment.mark_belong
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setMarkBelong(Boolean markBelong) {
        this.markBelong = markBelong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.replied
     *
     * @return the value of course_comment.replied
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Boolean getReplied() {
        return replied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.replied
     *
     * @param replied the value for course_comment.replied
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setReplied(Boolean replied) {
        this.replied = replied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment.comment
     *
     * @return the value of course_comment.comment
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment.comment
     *
     * @param comment the value for course_comment.comment
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}