package com.lh.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table course_play_history
 */
public class CoursePlayHistory {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_play_history.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_play_history.user_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   课程id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_play_history.course_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer courseId;

    /**
     * Database Column Remarks:
     *   章节id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_play_history.section_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer sectionId;

    /**
     * Database Column Remarks:
     *   课时id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_play_history.lesson_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer lessonId;

    /**
     * Database Column Remarks:
     *   历史播放节点(s)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_play_history.history_node
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer historyNode;

    /**
     * Database Column Remarks:
     *   最高历史播放节点
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_play_history.history_highest_node
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer historyHighestNode;

    /**
     * Database Column Remarks:
     *   记录创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_play_history.create_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_play_history.update_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   是否删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_play_history.is_del
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Boolean isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_play_history.id
     *
     * @return the value of course_play_history.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_play_history.id
     *
     * @param id the value for course_play_history.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_play_history.user_id
     *
     * @return the value of course_play_history.user_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_play_history.user_id
     *
     * @param userId the value for course_play_history.user_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_play_history.course_id
     *
     * @return the value of course_play_history.course_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_play_history.course_id
     *
     * @param courseId the value for course_play_history.course_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_play_history.section_id
     *
     * @return the value of course_play_history.section_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_play_history.section_id
     *
     * @param sectionId the value for course_play_history.section_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setSectionId(Integer sectionId) {
        this.sectionId = sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_play_history.lesson_id
     *
     * @return the value of course_play_history.lesson_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getLessonId() {
        return lessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_play_history.lesson_id
     *
     * @param lessonId the value for course_play_history.lesson_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setLessonId(Integer lessonId) {
        this.lessonId = lessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_play_history.history_node
     *
     * @return the value of course_play_history.history_node
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getHistoryNode() {
        return historyNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_play_history.history_node
     *
     * @param historyNode the value for course_play_history.history_node
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setHistoryNode(Integer historyNode) {
        this.historyNode = historyNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_play_history.history_highest_node
     *
     * @return the value of course_play_history.history_highest_node
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getHistoryHighestNode() {
        return historyHighestNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_play_history.history_highest_node
     *
     * @param historyHighestNode the value for course_play_history.history_highest_node
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setHistoryHighestNode(Integer historyHighestNode) {
        this.historyHighestNode = historyHighestNode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_play_history.create_time
     *
     * @return the value of course_play_history.create_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_play_history.create_time
     *
     * @param createTime the value for course_play_history.create_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_play_history.update_time
     *
     * @return the value of course_play_history.update_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_play_history.update_time
     *
     * @param updateTime the value for course_play_history.update_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_play_history.is_del
     *
     * @return the value of course_play_history.is_del
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_play_history.is_del
     *
     * @param isDel the value for course_play_history.is_del
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }
}