package com.lh.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   课程章节表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table course_section
 */
public class CourseSection {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_section.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   课程id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_section.course_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer courseId;

    /**
     * Database Column Remarks:
     *   章节名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_section.section_name
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String sectionName;

    /**
     * Database Column Remarks:
     *   章节描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_section.description
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String description;

    /**
     * Database Column Remarks:
     *   记录创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_section.create_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_section.update_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   是否删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_section.is_de
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Boolean isDe;

    /**
     * Database Column Remarks:
     *   排序字段
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_section.order_num
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer orderNum;

    /**
     * Database Column Remarks:
     *   状态，0:隐藏；1：待更新；2：已发布
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_section.status
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_section.id
     *
     * @return the value of course_section.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_section.id
     *
     * @param id the value for course_section.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_section.course_id
     *
     * @return the value of course_section.course_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_section.course_id
     *
     * @param courseId the value for course_section.course_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_section.section_name
     *
     * @return the value of course_section.section_name
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getSectionName() {
        return sectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_section.section_name
     *
     * @param sectionName the value for course_section.section_name
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setSectionName(String sectionName) {
        this.sectionName = sectionName == null ? null : sectionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_section.description
     *
     * @return the value of course_section.description
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_section.description
     *
     * @param description the value for course_section.description
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_section.create_time
     *
     * @return the value of course_section.create_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_section.create_time
     *
     * @param createTime the value for course_section.create_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_section.update_time
     *
     * @return the value of course_section.update_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_section.update_time
     *
     * @param updateTime the value for course_section.update_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_section.is_de
     *
     * @return the value of course_section.is_de
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Boolean getIsDe() {
        return isDe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_section.is_de
     *
     * @param isDe the value for course_section.is_de
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setIsDe(Boolean isDe) {
        this.isDe = isDe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_section.order_num
     *
     * @return the value of course_section.order_num
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_section.order_num
     *
     * @param orderNum the value for course_section.order_num
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_section.status
     *
     * @return the value of course_section.status
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_section.status
     *
     * @param status the value for course_section.status
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}