package com.lh.entity;

/**
 * Database Table Remarks:
 *   课程
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table course
 */
public class CourseWithBLOBs extends Course {
    /**
     * Database Column Remarks:
     *   描述markdown
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_description_mark_down
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String courseDescriptionMarkDown;

    /**
     * Database Column Remarks:
     *   课程描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_description
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String courseDescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_description_mark_down
     *
     * @return the value of course.course_description_mark_down
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getCourseDescriptionMarkDown() {
        return courseDescriptionMarkDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_description_mark_down
     *
     * @param courseDescriptionMarkDown the value for course.course_description_mark_down
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setCourseDescriptionMarkDown(String courseDescriptionMarkDown) {
        this.courseDescriptionMarkDown = courseDescriptionMarkDown == null ? null : courseDescriptionMarkDown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_description
     *
     * @return the value of course.course_description
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getCourseDescription() {
        return courseDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_description
     *
     * @param courseDescription the value for course.course_description
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setCourseDescription(String courseDescription) {
        this.courseDescription = courseDescription == null ? null : courseDescription.trim();
    }
}