package com.lh.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   课程
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table course
 */
public class Course {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   课程名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_name
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String courseName;

    /**
     * Database Column Remarks:
     *   课程一句话简介
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.brief
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String brief;

    /**
     * Database Column Remarks:
     *   原价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.price
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Double price;

    /**
     * Database Column Remarks:
     *   原价标签
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.price_tag
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String priceTag;

    /**
     * Database Column Remarks:
     *   优惠价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.discounts
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Double discounts;

    /**
     * Database Column Remarks:
     *   优惠标签
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.discounts_tag
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String discountsTag;

    /**
     * Database Column Remarks:
     *   课程分享图片url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_img_url
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String courseImgUrl;

    /**
     * Database Column Remarks:
     *   是否新品
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.is_new
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Boolean isNew;

    /**
     * Database Column Remarks:
     *   广告语
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.is_new_des
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String isNewDes;

    /**
     * Database Column Remarks:
     *   最后操作者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.last_operator_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer lastOperatorId;

    /**
     * Database Column Remarks:
     *   自动上架时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.auto_online_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Date autoOnlineTime;

    /**
     * Database Column Remarks:
     *   记录创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.create_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.update_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   是否删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.is_del
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Boolean isDel;

    /**
     * Database Column Remarks:
     *   总时长(分钟)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.total_duration
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer totalDuration;

    /**
     * Database Column Remarks:
     *   课程列表展示图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.course_list_img
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String courseListImg;

    /**
     * Database Column Remarks:
     *   课程状态，0-草稿，1-上架
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.status
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   课程排序，用于后台保存草稿时用到
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.sort_num
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer sortNum;

    /**
     * Database Column Remarks:
     *   课程预览第一个字段
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.preview_first_field
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String previewFirstField;

    /**
     * Database Column Remarks:
     *   课程预览第二个字段
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.preview_second_field
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String previewSecondField;

    /**
     * Database Column Remarks:
     *   销量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.sales
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer sales;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.id
     *
     * @return the value of course.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_name
     *
     * @return the value of course.course_name
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_name
     *
     * @param courseName the value for course.course_name
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.brief
     *
     * @return the value of course.brief
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.brief
     *
     * @param brief the value for course.brief
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setBrief(String brief) {
        this.brief = brief == null ? null : brief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.price
     *
     * @return the value of course.price
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.price
     *
     * @param price the value for course.price
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.price_tag
     *
     * @return the value of course.price_tag
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getPriceTag() {
        return priceTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.price_tag
     *
     * @param priceTag the value for course.price_tag
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setPriceTag(String priceTag) {
        this.priceTag = priceTag == null ? null : priceTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.discounts
     *
     * @return the value of course.discounts
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Double getDiscounts() {
        return discounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.discounts
     *
     * @param discounts the value for course.discounts
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setDiscounts(Double discounts) {
        this.discounts = discounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.discounts_tag
     *
     * @return the value of course.discounts_tag
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getDiscountsTag() {
        return discountsTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.discounts_tag
     *
     * @param discountsTag the value for course.discounts_tag
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setDiscountsTag(String discountsTag) {
        this.discountsTag = discountsTag == null ? null : discountsTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_img_url
     *
     * @return the value of course.course_img_url
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getCourseImgUrl() {
        return courseImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_img_url
     *
     * @param courseImgUrl the value for course.course_img_url
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setCourseImgUrl(String courseImgUrl) {
        this.courseImgUrl = courseImgUrl == null ? null : courseImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.is_new
     *
     * @return the value of course.is_new
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Boolean getIsNew() {
        return isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.is_new
     *
     * @param isNew the value for course.is_new
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setIsNew(Boolean isNew) {
        this.isNew = isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.is_new_des
     *
     * @return the value of course.is_new_des
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getIsNewDes() {
        return isNewDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.is_new_des
     *
     * @param isNewDes the value for course.is_new_des
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setIsNewDes(String isNewDes) {
        this.isNewDes = isNewDes == null ? null : isNewDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.last_operator_id
     *
     * @return the value of course.last_operator_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getLastOperatorId() {
        return lastOperatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.last_operator_id
     *
     * @param lastOperatorId the value for course.last_operator_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setLastOperatorId(Integer lastOperatorId) {
        this.lastOperatorId = lastOperatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.auto_online_time
     *
     * @return the value of course.auto_online_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Date getAutoOnlineTime() {
        return autoOnlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.auto_online_time
     *
     * @param autoOnlineTime the value for course.auto_online_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setAutoOnlineTime(Date autoOnlineTime) {
        this.autoOnlineTime = autoOnlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.create_time
     *
     * @return the value of course.create_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.create_time
     *
     * @param createTime the value for course.create_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.update_time
     *
     * @return the value of course.update_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.update_time
     *
     * @param updateTime the value for course.update_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.is_del
     *
     * @return the value of course.is_del
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.is_del
     *
     * @param isDel the value for course.is_del
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.total_duration
     *
     * @return the value of course.total_duration
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getTotalDuration() {
        return totalDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.total_duration
     *
     * @param totalDuration the value for course.total_duration
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setTotalDuration(Integer totalDuration) {
        this.totalDuration = totalDuration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.course_list_img
     *
     * @return the value of course.course_list_img
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getCourseListImg() {
        return courseListImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.course_list_img
     *
     * @param courseListImg the value for course.course_list_img
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setCourseListImg(String courseListImg) {
        this.courseListImg = courseListImg == null ? null : courseListImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.status
     *
     * @return the value of course.status
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.status
     *
     * @param status the value for course.status
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.sort_num
     *
     * @return the value of course.sort_num
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.sort_num
     *
     * @param sortNum the value for course.sort_num
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.preview_first_field
     *
     * @return the value of course.preview_first_field
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getPreviewFirstField() {
        return previewFirstField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.preview_first_field
     *
     * @param previewFirstField the value for course.preview_first_field
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setPreviewFirstField(String previewFirstField) {
        this.previewFirstField = previewFirstField == null ? null : previewFirstField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.preview_second_field
     *
     * @return the value of course.preview_second_field
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getPreviewSecondField() {
        return previewSecondField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.preview_second_field
     *
     * @param previewSecondField the value for course.preview_second_field
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setPreviewSecondField(String previewSecondField) {
        this.previewSecondField = previewSecondField == null ? null : previewSecondField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.sales
     *
     * @return the value of course.sales
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.sales
     *
     * @param sales the value for course.sales
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }
}