package com.lh.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   课程留言点赞表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table course_comment_favorite_record
 */
public class CourseCommentFavoriteRecord {
    /**
     * Database Column Remarks:
     *   用户评论点赞j记录ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment_favorite_record.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment_favorite_record.user_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   用户评论ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment_favorite_record.comment_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer commentId;

    /**
     * Database Column Remarks:
     *   是否删除，0：未删除（已赞），1：已删除（取消赞状态）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment_favorite_record.is_del
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Boolean isDel;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment_favorite_record.create_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course_comment_favorite_record.update_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment_favorite_record.id
     *
     * @return the value of course_comment_favorite_record.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment_favorite_record.id
     *
     * @param id the value for course_comment_favorite_record.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment_favorite_record.user_id
     *
     * @return the value of course_comment_favorite_record.user_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment_favorite_record.user_id
     *
     * @param userId the value for course_comment_favorite_record.user_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment_favorite_record.comment_id
     *
     * @return the value of course_comment_favorite_record.comment_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment_favorite_record.comment_id
     *
     * @param commentId the value for course_comment_favorite_record.comment_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment_favorite_record.is_del
     *
     * @return the value of course_comment_favorite_record.is_del
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment_favorite_record.is_del
     *
     * @param isDel the value for course_comment_favorite_record.is_del
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment_favorite_record.create_time
     *
     * @return the value of course_comment_favorite_record.create_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment_favorite_record.create_time
     *
     * @param createTime the value for course_comment_favorite_record.create_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course_comment_favorite_record.update_time
     *
     * @return the value of course_comment_favorite_record.update_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course_comment_favorite_record.update_time
     *
     * @param updateTime the value for course_comment_favorite_record.update_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}