package com.lh.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   支付订单信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pay_order
 */
public class PayOrder {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   订单号(唯一)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.order_no
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String orderNo;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.user_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   商品唯一标识(ID)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.product_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer productId;

    /**
     * Database Column Remarks:
     *   产品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.product_name
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String productName;

    /**
     * Database Column Remarks:
     *   金额,单位元
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.amount
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private BigDecimal amount;

    /**
     * Database Column Remarks:
     *   商品数量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.count
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer count;

    /**
     * Database Column Remarks:
     *   货币类型，cny-人民币 gbeans-勾豆
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.currency
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String currency;

    /**
     * Database Column Remarks:
     *   支付渠道：weChat-微信支付，aliPay-支付宝支付,applePay-苹果支付
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.channel
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String channel;

    /**
     * Database Column Remarks:
     *   订单状态：1-未支付 2-支付成功 3-支付失败 -1-订单失效
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.status
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   渠道中的状态码值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.channel_status
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Byte channelStatus;

    /**
     * Database Column Remarks:
     *   类型 1-购买课程 2-充值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.order_type
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Byte orderType;

    /**
     * Database Column Remarks:
     *   支付来源 1-app 2-h5 3-pc
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.source
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Byte source;

    /**
     * Database Column Remarks:
     *   用户支付IP
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.client_ip
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String clientIp;

    /**
     * Database Column Remarks:
     *   购买账号id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.buy_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String buyId;

    /**
     * Database Column Remarks:
     *   外部支付渠道交易号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.out_trade_no
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String outTradeNo;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.created_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Date createdTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.updated_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Date updatedTime;

    /**
     * Database Column Remarks:
     *   支付时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.pay_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Date payTime;

    /**
     * Database Column Remarks:
     *   商品订单编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.goods_order_no
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String goodsOrderNo;

    /**
     * Database Column Remarks:
     *   支付所使用的平台：1 拉勾 2 拉勾教育
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.platform
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer platform;

    /**
     * Database Column Remarks:
     *   微信类型, 参考自lg-wechat-boot项目中的wxinfo
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.wx_type
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer wxType;

    /**
     * Database Column Remarks:
     *   附加字段，KV json，例如:{"mobile":13020202,"success_url":123}
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.extra
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String extra;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.id
     *
     * @return the value of pay_order.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.id
     *
     * @param id the value for pay_order.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.order_no
     *
     * @return the value of pay_order.order_no
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.order_no
     *
     * @param orderNo the value for pay_order.order_no
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.user_id
     *
     * @return the value of pay_order.user_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.user_id
     *
     * @param userId the value for pay_order.user_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.product_id
     *
     * @return the value of pay_order.product_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.product_id
     *
     * @param productId the value for pay_order.product_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.product_name
     *
     * @return the value of pay_order.product_name
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.product_name
     *
     * @param productName the value for pay_order.product_name
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.amount
     *
     * @return the value of pay_order.amount
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.amount
     *
     * @param amount the value for pay_order.amount
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.count
     *
     * @return the value of pay_order.count
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.count
     *
     * @param count the value for pay_order.count
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.currency
     *
     * @return the value of pay_order.currency
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.currency
     *
     * @param currency the value for pay_order.currency
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.channel
     *
     * @return the value of pay_order.channel
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.channel
     *
     * @param channel the value for pay_order.channel
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.status
     *
     * @return the value of pay_order.status
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.status
     *
     * @param status the value for pay_order.status
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.channel_status
     *
     * @return the value of pay_order.channel_status
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Byte getChannelStatus() {
        return channelStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.channel_status
     *
     * @param channelStatus the value for pay_order.channel_status
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setChannelStatus(Byte channelStatus) {
        this.channelStatus = channelStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.order_type
     *
     * @return the value of pay_order.order_type
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Byte getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.order_type
     *
     * @param orderType the value for pay_order.order_type
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setOrderType(Byte orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.source
     *
     * @return the value of pay_order.source
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Byte getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.source
     *
     * @param source the value for pay_order.source
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setSource(Byte source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.client_ip
     *
     * @return the value of pay_order.client_ip
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getClientIp() {
        return clientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.client_ip
     *
     * @param clientIp the value for pay_order.client_ip
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setClientIp(String clientIp) {
        this.clientIp = clientIp == null ? null : clientIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.buy_id
     *
     * @return the value of pay_order.buy_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getBuyId() {
        return buyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.buy_id
     *
     * @param buyId the value for pay_order.buy_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setBuyId(String buyId) {
        this.buyId = buyId == null ? null : buyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.out_trade_no
     *
     * @return the value of pay_order.out_trade_no
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.out_trade_no
     *
     * @param outTradeNo the value for pay_order.out_trade_no
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.created_time
     *
     * @return the value of pay_order.created_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.created_time
     *
     * @param createdTime the value for pay_order.created_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.updated_time
     *
     * @return the value of pay_order.updated_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.updated_time
     *
     * @param updatedTime the value for pay_order.updated_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.pay_time
     *
     * @return the value of pay_order.pay_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.pay_time
     *
     * @param payTime the value for pay_order.pay_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.goods_order_no
     *
     * @return the value of pay_order.goods_order_no
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getGoodsOrderNo() {
        return goodsOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.goods_order_no
     *
     * @param goodsOrderNo the value for pay_order.goods_order_no
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setGoodsOrderNo(String goodsOrderNo) {
        this.goodsOrderNo = goodsOrderNo == null ? null : goodsOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.platform
     *
     * @return the value of pay_order.platform
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.platform
     *
     * @param platform the value for pay_order.platform
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setPlatform(Integer platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.wx_type
     *
     * @return the value of pay_order.wx_type
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getWxType() {
        return wxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.wx_type
     *
     * @param wxType the value for pay_order.wx_type
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setWxType(Integer wxType) {
        this.wxType = wxType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.extra
     *
     * @return the value of pay_order.extra
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getExtra() {
        return extra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.extra
     *
     * @param extra the value for pay_order.extra
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setExtra(String extra) {
        this.extra = extra == null ? null : extra.trim();
    }
}