package com.lh.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   广告区域表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table promotion_space
 */
public class PromotionSpace {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion_space.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion_space.name
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String name;

    /**
     * Database Column Remarks:
     *   广告位key
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion_space.spaceKey
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String spacekey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion_space.createTime
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion_space.updateTime
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion_space.isDel
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer isdel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion_space.id
     *
     * @return the value of promotion_space.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion_space.id
     *
     * @param id the value for promotion_space.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion_space.name
     *
     * @return the value of promotion_space.name
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion_space.name
     *
     * @param name the value for promotion_space.name
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion_space.spaceKey
     *
     * @return the value of promotion_space.spaceKey
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getSpacekey() {
        return spacekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion_space.spaceKey
     *
     * @param spacekey the value for promotion_space.spaceKey
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setSpacekey(String spacekey) {
        this.spacekey = spacekey == null ? null : spacekey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion_space.createTime
     *
     * @return the value of promotion_space.createTime
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion_space.createTime
     *
     * @param createtime the value for promotion_space.createTime
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion_space.updateTime
     *
     * @return the value of promotion_space.updateTime
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion_space.updateTime
     *
     * @param updatetime the value for promotion_space.updateTime
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion_space.isDel
     *
     * @return the value of promotion_space.isDel
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion_space.isDel
     *
     * @param isdel the value for promotion_space.isDel
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }
}