package com.lh.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   广告表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table promotion_ad
 */
public class PromotionAd {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion_ad.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   广告名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion_ad.name
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String name;

    /**
     * Database Column Remarks:
     *   广告位id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion_ad.spaceId
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer spaceid;

    /**
     * Database Column Remarks:
     *   精确搜索关键词
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion_ad.keyword
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String keyword;

    /**
     * Database Column Remarks:
     *   文字一
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion_ad.text
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String text;

    /**
     * Database Column Remarks:
     *   链接一
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion_ad.link
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String link;

    /**
     * Database Column Remarks:
     *   开始时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion_ad.startTime
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Date starttime;

    /**
     * Database Column Remarks:
     *   结束时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion_ad.endTime
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion_ad.createTime
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion_ad.updateTime
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion_ad.status
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   优先级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion_ad.priority
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion_ad.img
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String img;

    /**
     * Database Column Remarks:
     *   静态广告的内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promotion_ad.htmlContent
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String htmlcontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion_ad.id
     *
     * @return the value of promotion_ad.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion_ad.id
     *
     * @param id the value for promotion_ad.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion_ad.name
     *
     * @return the value of promotion_ad.name
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion_ad.name
     *
     * @param name the value for promotion_ad.name
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion_ad.spaceId
     *
     * @return the value of promotion_ad.spaceId
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getSpaceid() {
        return spaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion_ad.spaceId
     *
     * @param spaceid the value for promotion_ad.spaceId
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setSpaceid(Integer spaceid) {
        this.spaceid = spaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion_ad.keyword
     *
     * @return the value of promotion_ad.keyword
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion_ad.keyword
     *
     * @param keyword the value for promotion_ad.keyword
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion_ad.text
     *
     * @return the value of promotion_ad.text
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion_ad.text
     *
     * @param text the value for promotion_ad.text
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion_ad.link
     *
     * @return the value of promotion_ad.link
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion_ad.link
     *
     * @param link the value for promotion_ad.link
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion_ad.startTime
     *
     * @return the value of promotion_ad.startTime
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion_ad.startTime
     *
     * @param starttime the value for promotion_ad.startTime
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion_ad.endTime
     *
     * @return the value of promotion_ad.endTime
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion_ad.endTime
     *
     * @param endtime the value for promotion_ad.endTime
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion_ad.createTime
     *
     * @return the value of promotion_ad.createTime
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion_ad.createTime
     *
     * @param createtime the value for promotion_ad.createTime
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion_ad.updateTime
     *
     * @return the value of promotion_ad.updateTime
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion_ad.updateTime
     *
     * @param updatetime the value for promotion_ad.updateTime
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion_ad.status
     *
     * @return the value of promotion_ad.status
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion_ad.status
     *
     * @param status the value for promotion_ad.status
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion_ad.priority
     *
     * @return the value of promotion_ad.priority
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion_ad.priority
     *
     * @param priority the value for promotion_ad.priority
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion_ad.img
     *
     * @return the value of promotion_ad.img
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion_ad.img
     *
     * @param img the value for promotion_ad.img
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promotion_ad.htmlContent
     *
     * @return the value of promotion_ad.htmlContent
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getHtmlcontent() {
        return htmlcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promotion_ad.htmlContent
     *
     * @param htmlcontent the value for promotion_ad.htmlContent
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setHtmlcontent(String htmlcontent) {
        this.htmlcontent = htmlcontent == null ? null : htmlcontent.trim();
    }
}