package com.lh.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   用户课程订单表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_course_order
 */
public class UserCourseOrder {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course_order.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   订单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course_order.order_no
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private String orderNo;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course_order.user_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   课程id，根据订单中的课程类型来选择
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course_order.course_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer courseId;

    /**
     * Database Column Remarks:
     *   活动课程id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course_order.activity_course_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Integer activityCourseId;

    /**
     * Database Column Remarks:
     *   订单来源类型: 1 用户下单购买 2 后台添加专栏
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course_order.source_type
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Byte sourceType;

    /**
     * Database Column Remarks:
     *   当前状态: 0已创建 10未支付 20已支付 30已取消 40已过期 
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course_order.status
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course_order.create_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course_order.update_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   是否删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_course_order.is_del
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    private Byte isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course_order.id
     *
     * @return the value of user_course_order.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course_order.id
     *
     * @param id the value for user_course_order.id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course_order.order_no
     *
     * @return the value of user_course_order.order_no
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course_order.order_no
     *
     * @param orderNo the value for user_course_order.order_no
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course_order.user_id
     *
     * @return the value of user_course_order.user_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course_order.user_id
     *
     * @param userId the value for user_course_order.user_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course_order.course_id
     *
     * @return the value of user_course_order.course_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course_order.course_id
     *
     * @param courseId the value for user_course_order.course_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course_order.activity_course_id
     *
     * @return the value of user_course_order.activity_course_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Integer getActivityCourseId() {
        return activityCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course_order.activity_course_id
     *
     * @param activityCourseId the value for user_course_order.activity_course_id
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setActivityCourseId(Integer activityCourseId) {
        this.activityCourseId = activityCourseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course_order.source_type
     *
     * @return the value of user_course_order.source_type
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Byte getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course_order.source_type
     *
     * @param sourceType the value for user_course_order.source_type
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setSourceType(Byte sourceType) {
        this.sourceType = sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course_order.status
     *
     * @return the value of user_course_order.status
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course_order.status
     *
     * @param status the value for user_course_order.status
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course_order.create_time
     *
     * @return the value of user_course_order.create_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course_order.create_time
     *
     * @param createTime the value for user_course_order.create_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course_order.update_time
     *
     * @return the value of user_course_order.update_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course_order.update_time
     *
     * @param updateTime the value for user_course_order.update_time
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_course_order.is_del
     *
     * @return the value of user_course_order.is_del
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public Byte getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_course_order.is_del
     *
     * @param isDel the value for user_course_order.is_del
     *
     * @mbg.generated Tue Jun 20 09:40:37 CST 2023
     */
    public void setIsDel(Byte isDel) {
        this.isDel = isDel;
    }
}